name: AntiCheatUnit
version: 1.4
main: kr.mcv.lightfrog.anticheatunit.Anticheatunit
api-version: 1.13
description: Matrix Anticheat Advanced First Addon

softdepend: [ ProtocolLib, Matrix ]

commands:
  anticheatunit:
    description: anticheatunit base commanda